### ISSUE TITLE
[Request] Merging Kolors LoRA to Kolors checkpoint

### ISSUE THREAD

**Issue by lekima** [lrzjason/T2ITrainer#10]
Hi, is it possible to support merging a Kolors LoRA to Kolors checkpoint?

**Comment by lrzjason** [comment]
You could use this plugin to load https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ/tree/main kolors model and use lora loader to load lora.
After that, you could use merge sdxl node to merge the lora and models.
Finally, you could use this plugin https://github.com/lrzjason/Comfyui-Kolors-Utils to save as kolors unet or kolors checkpoint.

**Comment by lekima** [comment]
@lrzjason thank you, I'm not sure if I do the 2nd step (_use merge sdxl node to merge the lora and models_) right, could you please help confirm whether the workflow is correct?

![image](https://github.com/user-attachments/assets/1a0fcc7e-a961-40de-a434-38eab137eaef)

**Comment by lrzjason** [comment]
Yes, it is. You could also use saveKolors node to save as sd format checkpoint.

**Comment by lekima** [comment]
@lrzjason nice, I'll switch to the saveKolors node! Btw do you know if I can run this merge workflow with 16GB VRAM?

**Comment by lrzjason** [comment]
You might try. I am not sure

**Comment by lekima** [comment]
Will try, thanks a lot for your help!
