### ISSUE TITLE
能微调训练kolors 的 inpainting模型吗？

### ISSUE THREAD

**Issue by WM-Wu** [lrzjason/T2ITrainer#14]

**Comment by lrzjason** [comment]
不能

**Comment by WM-Wu** [comment]
感谢回复！后续有inpainting微调代码研究计划吗

**Comment by lrzjason** [comment]
暂时没有，官方的inpaint模型好像已经很不错了，如果你又特别的需求我可以考虑一下

**Comment by WM-Wu** [comment]
哈哈感谢回复。我只是想找个inpainting模型的微调代码作为学习材料，一直没有找到关于inpaint微调的部分的代码
