### ISSUE TITLE
help ！！ T2ITrainer\venv\lib\site-packages\gradio\blocks.py", line 2255, in launch     raise ValueError(

### ISSUE THREAD

**Issue by isaac-bj** [lrzjason/T2ITrainer#5]
(venv) C:\soft\T2ITrainer>python ui.py
Loaded configuration from config.json
Running on local URL:  http://127.0.0.1:7860
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "C:\soft\T2ITrainer\ui.py", line 372, in <module>
    demo.launch()
  File "C:\soft\T2ITrainer\venv\lib\site-packages\gradio\blocks.py", line 2255, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by lrzjason** [comment]
If you are using proxy, please close it first.

**Comment by isaac-bj** [comment]
> If you are using proxy, please close it first.

It's been solved, thank you
