### ISSUE TITLE
How to use lora with Kolors?

### ISSUE THREAD

**Issue by lekima** [lrzjason/T2ITrainer#8]
Hi,

You mentioned that we can "use the normal lora loader in ComfyUI". Could you please guide me a bit on the node setup?
Lora Loader requires a Clip input/output and there isn't a way to connect this with either Kolors Model Loader or ChatGLM3TextEncode.

**Comment by emojiiii** [comment]
https://github.com/kijai/ComfyUI-KwaiKolorsWrapper

**Comment by lekima** [comment]
@emojiiii sorry but I can't manage to find instructions/workflows that involve a Lora node, is it possible that you can help provide more pointers?

**Comment by emojiiii** [comment]
https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/blob/main/examples/kolors_example.json

**Comment by lekima** [comment]
@emojiiii appreciate it, but this workflow doesn't include any Lora node/loader ;( do you mind being a bit more specific? very sorry for noob question

**Comment by emojiiii** [comment]
[kolors with lora.json](https://github.com/user-attachments/files/16369535/kolors.with.lora.json)

**Comment by lekima** [comment]
@emojiiii this works! thank you so much! Really appreciate it!

**Comment by lekima** [comment]
The issue is resolved
